version: '3.9'
services:
  db: 
    image: "postgres:17"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USER?:DB_USER not set}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD?:DB_PWD not set}"
      POSTGRES_DB: "ohmdb"
    volumes:
      - ./db:/var/lib/postgressql/data
    deploy:
      resources:
        limits:
          memory: 1gb
  app: 
    build: 
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    image: ku-polls
    command: 
      - /bin/sh
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    env_file: .env
    environment:
      SECRET_KEY: "${SECRET_KEY?:SECRET_KEY not set}"
      DATABASE_USERNAME: "${DATABASE_USER?:DB_USER not set}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD?:DB_PWD not set}"
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    links:
      - db
    depends_on:
      db: 
        condition: service_healthy
    ports:
      - '8000:8000'
    deploy:
      resources:
        limits:
          memory: 256mb